"use strict";

// File-backed chat threads (server-side conversation memory).
//
// Each user gets a chat/ directory under their artifacts dir. A thread is one
// JSON file holding the full OpenAI message array (system/user/assistant/tool),
// so multi-turn context is preserved without the client resending history — the
// client only keeps a threadId.
//
// Layout: <userDir>/chat/<threadId>.json
//   { threadId, title, createdAt, updatedAt, messages: [ ...OpenAI messages ] }
//
// A thread answered by a chat backend that keeps its own transcript carries one
// extra field, written through setMeta(): `cursorChatId`, the id the Cursor CLI
// resumes. The message array is still maintained either way — it is what the UI
// renders and what the thread list and summarize read.

let fs = require('fs');
let path = require('path');
let crypto = require('crypto');
let propertiesReader = require('properties-reader');
let paths = require('../paths');

let props = propertiesReader(path.resolve(__dirname, '../../config.properties'));

function getChatDirName() {
    return props.get('server.chatDirName') || 'chat';
}

function getChatDir(userName) {
    let dir = path.join(paths.getUserDir(userName), getChatDirName());
    fs.mkdirSync(dir, { recursive: true });
    return dir;
}

// Reject anything that isn't a plain uuid-ish id so a threadId can never escape
// the chat directory via path traversal. Stricter than pathSafety.isSafeSegment
// on purpose: a threadId is always generated by newThreadId(), never typed, so
// there is no legitimate name to accommodate here.
function isSafeThreadId(threadId) {
    return typeof threadId === 'string' && /^[a-zA-Z0-9_-]{1,64}$/.test(threadId);
}

// The check lives here rather than in each caller, because the five write paths
// below (create/append/setMeta/rename/delete) all reach the filesystem through
// this one function — gating the readers alone would leave the writes open.
function threadFile(userName, threadId) {
    if (!isSafeThreadId(threadId)) {
        let err = new Error('invalid threadId.');
        err.statusCode = 400;
        throw err;
    }
    return path.join(getChatDir(userName), threadId + '.json');
}

function newThreadId() {
    return crypto.randomUUID();
}

// Create a new empty thread and persist it. Returns the thread object.
function createThread(userName, title) {
    let now = new Date().toISOString();
    let thread = {
        threadId: newThreadId(),
        title: title || 'New chat',
        createdAt: now,
        updatedAt: now,
        messages: []
    };
    fs.writeFileSync(threadFile(userName, thread.threadId), JSON.stringify(thread, null, 2));
    return thread;
}

// Load a thread, or null if it doesn't exist / id is unsafe.
function getThread(userName, threadId) {
    if (!isSafeThreadId(threadId)) {
        return null;
    }
    let file = threadFile(userName, threadId);
    if (!fs.existsSync(file)) {
        return null;
    }
    try {
        return JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (e) {
        return null;
    }
}

// Get an existing thread or create a fresh one if threadId is missing/unknown.
function getOrCreateThread(userName, threadId, title) {
    let existing = getThread(userName, threadId);
    if (existing) {
        return existing;
    }
    return createThread(userName, title);
}

// Persist the full message array for a thread; refreshes updatedAt and derives a
// title from the first user message if still default.
function saveMessages(userName, threadId, messages, title) {
    let thread = getThread(userName, threadId) || createThread(userName, title);
    thread.messages = messages;
    thread.updatedAt = new Date().toISOString();
    if ((!thread.title || thread.title === 'New chat') && Array.isArray(messages)) {
        let firstUser = messages.find(m => m.role === 'user' && typeof m.content === 'string');
        if (firstUser) {
            thread.title = firstUser.content.slice(0, 60);
        }
    }
    fs.writeFileSync(threadFile(userName, thread.threadId), JSON.stringify(thread, null, 2));
    return thread;
}

// List threads (most-recently-updated first) as lightweight summaries.
function listThreads(userName) {
    let dir = getChatDir(userName);
    let files;
    try {
        files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));
    } catch (e) {
        return [];
    }
    let threads = [];
    for (let f of files) {
        try {
            let t = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
            threads.push({
                threadId: t.threadId,
                title: t.title || 'New chat',
                createdAt: t.createdAt,
                updatedAt: t.updatedAt,
                messageCount: Array.isArray(t.messages) ? t.messages.length : 0
            });
        } catch (e) {
            // skip unreadable file
        }
    }
    threads.sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt)));
    return threads;
}

// Rename a thread's title (user-supplied). Does NOT bump updatedAt, so the
// sidebar ordering stays stable across a rename. Returns the updated thread, or
// null if it doesn't exist / the title is empty.
function renameThread(userName, threadId, title) {
    let thread = getThread(userName, threadId);
    if (!thread) {
        return null;
    }
    let clean = String(title == null ? '' : title).trim().slice(0, 120);
    if (!clean) {
        return null;
    }
    thread.title = clean;
    fs.writeFileSync(threadFile(userName, thread.threadId), JSON.stringify(thread, null, 2));
    return thread;
}

/**
 * Merge extra fields onto a thread without touching its messages.
 *
 * For state that belongs to the thread but is not part of the conversation — the
 * Cursor backend's own chat id, which is what lets `--resume` continue a
 * conversation whose transcript lives at the backend. Deliberately does not bump
 * updatedAt (this is bookkeeping, not activity) and refuses to overwrite the
 * identity or message fields, so a careless caller cannot orphan a thread.
 */
const PROTECTED_THREAD_FIELDS = ['threadId', 'messages', 'createdAt'];

function setMeta(userName, threadId, patch) {
    let thread = getThread(userName, threadId);
    if (!thread || !patch) {
        return null;
    }
    Object.keys(patch).forEach(function (key) {
        if (PROTECTED_THREAD_FIELDS.indexOf(key) < 0) {
            thread[key] = patch[key];
        }
    });
    fs.writeFileSync(threadFile(userName, thread.threadId), JSON.stringify(thread, null, 2));
    return thread;
}

function deleteThread(userName, threadId) {
    if (!isSafeThreadId(threadId)) {
        return false;
    }
    let file = threadFile(userName, threadId);
    if (fs.existsSync(file)) {
        fs.unlinkSync(file);
        return true;
    }
    return false;
}

module.exports = {
    createThread: createThread,
    getThread: getThread,
    getOrCreateThread: getOrCreateThread,
    saveMessages: saveMessages,
    listThreads: listThreads,
    renameThread: renameThread,
    setMeta: setMeta,
    deleteThread: deleteThread,
    isSafeThreadId: isSafeThreadId
};
